/*
 * PIT.h
 *
 *  Created on: 2017. 7. 29.
 *      Author: Yummy
 */

#ifndef __PIT_H__
#define __PIT_H__

#include <Types.h>

#pragma once
// Macro
#define PIT_FREQUENCY			1193182
#define MSTOCNT(x)			(PIT_FREQUENCY * (x) / 1000)
#define USTOCNT(x)			(PIT_FREQUENCY * (x) / 1000000)

// I/O Port
#define PIT_PORT_CONTROL		0x43
#define PIT_PORT_COUNTER_ZERO		0x40
#define PIT_PORT_COUNTER_ONE		0x41
#define PIT_PORT_COUNTER_TWO		0x42

// Mode
#define PIT_CONTROL_COUNTER_ZERO	0x00
#define PIT_CONTROL_COUNTER_ONE		0x40
#define PIT_CONTROL_COUNTER_TWO		0x80
#define PIT_CONTROL_LSBMSBRW		0x30
#define PIT_CONTROL_LATCH		0x00
#define PIT_CONTROL_MODE_ZERO		0x00
#define PIT_CONTROL_MODE_TWO		0x04

// Binary Or BCD
#define PIT_CONTROL_BINARYCOUNTER	0x00
#define PIT_CONTROL_BCDCOUNTER		0x01

#define PIT_COUNTER_ZERO_ONCE		(PIT_CONTROL_COUNTER_ZERO | PIT_CONTROL_LSBMSBRW | PIT_CONTROL_MODE_ZERO | PIT_CONTROL_BINARYCOUNTER)
#define PIT_COUNTER_ZERO_PERIODIC	(PIT_CONTROL_COUNTER_ZERO | PIT_CONTROL_LSBMSBRW | PIT_CONTROL_MODE_TWO | PIT_CONTROL_BINARYCOUNTER)
#define PIT_COUNTER_ZERO_LATCH		(PIT_CONTROL_COUNTER_ZERO | PIT_CONTROL_LATCH)

void initPIT(WORD cnt, BOOL term);
WORD readCntZero(void);
void waitPIT(WORD cnt);

#endif /*__PIT_H__*/
