/*
 * SysCallList.h
 *
 *  Created on: 2018. 6. 14.
 *      Author: Yummy
 */

#ifndef __SYSCALLLIST_H__
#define __SYSCALLLIST_H__

#pragma once

// 콘솔 IO 관련
#define SYSCALL_CSPRINT				0
#define SYSCALL_SETCURSOR			1
#define SYSCALL_GETCURSOR			2
#define SYSCALL_CLEARMONITOR		3
#define SYSCALL_GETCH				4

// 동적 메모리 할당 및 해제 관련
#define SYSCALL_MALLOC				5
#define SYSCALL_FREE				6

// 파일 및 디렉터리 IO 관련
#define SYSCALL_FOPEN				7
#define SYSCALL_FREAD				8
#define SYSCALL_FWRITE				9
#define SYSCALL_FSEEK				10
#define SYSCALL_FCLOSE				11
#define SYSCALL_FREMOVE				12
#define SYSCALL_DOPEN				13
#define SYSCALL_DREAD				14
#define SYSCALL_DREWIND				15
#define SYSCALL_DCLOSE				16
#define SYSCALL_ISFOPEN				17

// 하드 디스크 IO 관련
#define SYSCALL_READ_HDDSECTOR		18
#define SYSCALL_WRITE_HDDSECTOR		19

// 태스크 및 스케줄러 관련
#define SYSCALL_CREATETASK			20
#define SYSCALL_SCHEDULE			21
#define SYSCALL_ALTERPRIORITY		22
#define SYSCALL_TASKFIN				23
#define SYSCALL_TASKEXIT			24
#define SYSCALL_GETTASKCNT			25
#define SYSCALL_ISTASKEXIST			26
#define SYSCALL_GETPROCLOAD			27
#define SYSCALL_ALTERAFFINITY		28

// GUI 시스템 관련
#define SYSCALL_GETBACKGROUNDID		31
#define SYSCALL_GETMONAREA			32
#define SYSCALL_CREATEWIN			33
#define SYSCALL_DELWIN				34
#define SYSCALL_SHOWWIN				35
#define SYSCALL_FINDWINPOINT		36
#define SYSCALL_FINDWINTITLE		37
#define SYSCALL_ISWINEXIST			38
#define SYSCALL_GETTOPWIN			39
#define SYSCALL_MOVEWINTOP			40
#define SYSCALL_ISINTITLE			41
#define SYSCALL_ISCLOSEBTN			42
#define SYSCALL_MOVEWIN				43
#define SYSCALL_RESIZEWIN			44
#define SYSCALL_GETWINAREA			45
#define SYSCALL_UPDATEMONID			46
#define SYSCALL_UPDATEMONWINAREA	47
#define SYSCALL_UPDATEMONAREA		48
#define SYSCALL_EVENTTOWIN			49
#define SYSCALL_WINTOEVENT			50
#define SYSCALL_DRAWWINFRAME		51
#define SYSCALL_DRAWWINBACKGROUND	52
#define SYSCALL_DRAWWINTITLE		53
#define SYSCALL_DRAWBTN				54
#define SYSCALL_DRAWPIXEL			55
#define SYSCALL_DRAWLINE			56
#define SYSCALL_DRAWRECT			57
#define SYSCALL_DRAWCIRCLE			58
#define SYSCALL_DRAWTEXT			59
#define SYSCALL_MOVECURSOR			60
#define SYSCALL_GETWINCURSOR		61
#define SYSCALL_BITBLT				62

// JPEG 디코더 관련
#define SYSCALL_JPGINIT				63
#define SYSCALL_JPGDECODE			64

// RTC 관련
#define SYSCALL_READTIME			65
#define SYSCALL_READDATE			66

// 시리얼 IO 관련
#define SYSCALL_SENDSERIALDATA		67
#define SYSCALL_RECVSERIALDATA		68
#define SYSCALL_CLEARSERIALFIFO		69

// 유틸 관련
#define SYSCALL_GETTOTALMEMSIZE		70
#define SYSCALL_GETTICKCNT			71
#define SYSCALL_SLEEP				72
#define SYSCALL_ISGUIMODE			73
#define SYSCALL_TEST				0xFFFFFFFF

#endif	/* __SYSCALLLIST_H__ */
